VERSION = "V0.0.1"
DEBUG_MODE = True

# Blocks
BLOCK_SIZE = 48
HORIZONTAL_BLOCKS = 16
VERTICAL_BLOCKS = 12

# Window settings
WINDOW_TITLE = "Flatted Beta"
# Width & height depend on blocks
DEFAULT_WINDOW_WIDTH = HORIZONTAL_BLOCKS * BLOCK_SIZE
DEFAULT_WINDOW_HEIGHT = VERTICAL_BLOCKS * BLOCK_SIZE
