VERSION = "V0.0.1"
DEBUG_MODE = True

# Resources
INDEX_FILE = "./resources/index.json"

# Blocks
BLOCK_SIZE = 48
HORIZONTAL_BLOCKS = 16
VERTICAL_BLOCKS = 12

# Grid
GRID_WIDTH = HORIZONTAL_BLOCKS * 3
GRID_HEIGHT = 24
GRID_OFFEST_X = 0
GRID_OFFEST_Y = -(GRID_HEIGHT - VERTICAL_BLOCKS) * BLOCK_SIZE

# Window settings
WINDOW_TITLE = "Flatted %s" % VERSION
# Width & height depend on blocks
DEFAULT_WINDOW_WIDTH = HORIZONTAL_BLOCKS * BLOCK_SIZE
DEFAULT_WINDOW_HEIGHT = VERTICAL_BLOCKS * BLOCK_SIZE
